import Head from "next/head";
import Image from "next/image";

function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex item-center justify-center w-full h-screen">
        <div className="max-w-md mx-auto bg-white overflow-hidden md:max-w-2xl rounded-2xl shadow-lg h-fit">
          <div className="md:flex-col w-fit">
            <img
              className="h-48 w-full object-cover md:h-full md:w-48"
              src="/nana.jpg"
              alt="nana baidoo's face"
            />
            <div className="p-4">
              <div className="uppercase tracking-wide text-sm text-indigo-500 font-bold">
                Nana Baidoo</div>
              <div className="block mt-1 text-lg leading-tight font-medium text-black">
                Software Engineer</div>
              <h1 className="font-medium"> Dapp Developer </h1>
                <br />
              <h2 className="text-sm">UI/UX Designer</h2>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
export default Home;
